CREATE TABLE ITEM (
IDITEM INTEGER NOT NULL PRIMARY KEY,
DESCITEM VARCHAR(100)
);

CREATE TABLE PEDIDOCAB (
IDPEDIDOCAB INTEGER NOT NULL PRIMARY KEY,
DTEMISSAO DATE,
NUMERO INTEGER,
CLENTE VARCHAR(100)
);

CREATE TABLE PEDIDOITEM (
IDPEDIDOITEM INTEGER NOT NULL PRIMARY KEY,
IDPEDIDOCAB INTEGER NOT NULL,
IDITEM INTEGER NOT NULL,
QUANTIDADE DOUBLE PRECISION,
VALORUNIT DOUBLE PRECISION,
VALORTOTAL DOUBLE PRECISION,
CONSTRAINT FK_PEDIDOCAB FOREIGN KEY (IDPEDIDOCAB) REFERENCES PEDIDOCAB (IDPEDIDOCAB),
CONSTRAINT FK_ITEM FOREIGN KEY (IDITEM) REFERENCES ITEM (IDITEM)
);